sudo: required
services:
    - docker
    
before_install:
    - docker build -t dockerak -f Dockerfile.dev .

script:
    - docker run -e CI=true dockerak npm run test    



deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "my-react"
  env: "Myreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-456532073387"
  bucket_path: "my-reactt"
  on:
  branch: master